apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: 'jnlp'
    image: 'jenkins/jnlp-slave:3.27-1-alpine'
    tty: true
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"

  - name: 'docker'
    image: 'docker:18.02'
    ttyEnabled: true
    command: 'cat'
    resourceRequestMemory: '1024Mi'
    env:
    - name: RUNNING_IN
      value: "docker"
    tty: true
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"

  - name: 'helm'
    image: 'ibmcom/k8s-helm:v2.6.0'
    ttyEnabled: true
    command: 'cat'
    tty: true
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"

  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
