# apiVersion: v1
# kind: Pod
# metadata:
#   labels:
#     some-label: some-label-value
# spec:
#   containers:
#   - name: buildtools
#     image: 350922719856.dkr.ecr.us-west-2.amazonaws.com/fe-buildtools:latest
#     command:
#     - cat
#     tty: true
#     env:
#     - name: 'HOME'
#       value: '.'
#     - name: 'ARTIFACTS_BUCKET'
#       value: 'jobs-service-artifacts'
#     - name: 'AWS_DEFAULT_REGION'
#       value: 'us-west-2'
#     - name: 'environment'
#       value: "${buildEnvironment}"
#     - name: 'CI'
#       value: 'true'
#     - name: 'HUSKY_SKIP_INSTALL'
#       value: 'true'
#     resources:
#       requests:
#         memory: "1024Mi"
#         cpu: "500m"
#       limits:
#         memory: "2048Mi"
#         cpu: "1000m"
#     volumeMounts:
#       - name: dockersock
#         mountPath: "/var/run/docker.sock"
#   volumes:
#     - name: dockersock
#       hostPath:
#         path: /var/run/docker.sock


apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: 'jnlp'
    image: 'jenkins/jnlp-slave:3.27-1-alpine'
    args: '${computer.jnlpmac} ${computer.name}'
    tty: true
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"
  - name: 'docker'
    image: 'docker:18.02'
    ttyEnabled: true
    command: 'cat'
    resourceRequestMemory: '1024Mi'
    env:
    - name: RUNNING_IN
      value: "docker"
    tty: true
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"

  - name: 'helm'
    image: 'ibmcom/k8s-helm:v2.6.0'
    ttyEnabled: true
    command: 'cat'
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
    tty: true
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"
